name: Run Laravel & Postman Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: sqlite, pdo_sqlite
          tools: composer

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress

      - name: Set up environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run migrations and seed database
        run: |
          php artisan migrate --seed --env=testing

      - name: Run Pest tests
        run: |
          vendor/bin/pest tests/Feature --colors=always
